import { Geist, Geist_Mono } from "next/font/google";
import { Orbitron } from "next/font/google";
import Background from "./components/Background";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"], // choose what you need
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${orbitron.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
      <Navbar />
      <Background />
        {children}
      </body>
    </html>
  );
}
